//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryAirfield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Используемая_экипировка
    {
        [Display(Name = "ID экипировки")]
        public int ID_экипировки { get; set; }
        [Display(Name = "ID Сотрудника")]
        public int ID_Сотрудника { get; set; }
        [Display(Name = "Защитный костюм")]
        [Required(ErrorMessage = "Введите защитный костюм")]
        public string Защитный_костюм { get; set; }
        [Display(Name = "Наличие авиационного спасательного пояса")]
        public bool Наличие_авиационного_спасательного_пояса { get; set; }
        [Display(Name = "Наплечные знаки различия/погоны")]
        [Required(ErrorMessage = "Введите наплечные знаки различия/погоны")]
        public string Наплечные_знаки_различия_или_погоны { get; set; }
        [Display(Name = "Тип экипировки")]
        [Required(ErrorMessage = "Введите тип экипировки")]
        public string Тип_экипировки { get; set; }

        public virtual Сотрудник_аэродрома Сотрудник_аэродрома { get; set; }
    }
}
