//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryAirfield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Навигационная_система
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Навигационная_система()
        {
            this.Воздушное_судно = new HashSet<Воздушное_судно>();
        }

        [Display(Name = "ID навигационной системы")]
        public int ID_навигационной_системы { get; set; }
        [Display(Name = "Средняя дальность обнаружения воздушной цели")]
        public int Средняя_дальность_обнаружения_воздушной_цели { get; set; }
        [Display(Name = "Количество одновременно-сопровождаемых целей")]
        public int Количество_одновременно_сопровождаемых_целей { get; set; }
        [Display(Name = "Количество одновременно-атакуемых целей")]
        public int Количество_одновременно_атакуемых_целей { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Воздушное_судно> Воздушное_судно { get; set; }
    }
}
