//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryAirfield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Полеты
    {
        [Display(Name = "Номер рейса")]
        public int Номер_рейса { get; set; }
        [Display(Name = "Место вылета")]
        [Required(ErrorMessage = "Введите место вылета")]
        public string Место_вылета { get; set; }
        [Display(Name = "Дата и время вылета")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime Дата_и_время_вылета { get; set; }
        [Display(Name = "Место прибытия")]
        [Required(ErrorMessage = "Введите место прибытия")]
        public string Место_прибытия { get; set; }
        [Display(Name = "Дата и время прилета")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime Дата_и_время_прилета { get; set; }
        [Display(Name = "Номер взлётной полосы")]
        public int Номер_взлетной_полосы { get; set; }
        [Display(Name = "Расстояние (км)")]
        public int Расстояние_в_км_ { get; set; }
        [Display(Name = "ID Воздушного судна")]
        public int ID_Воздушного_судна { get; set; }
        [Display(Name = "Боевой полёт")]
        public bool Боевой_полет { get; set; }

        public virtual Воздушное_судно Воздушное_судно { get; set; }
    }
}
