//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryAirfield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Сотрудник_аэродрома
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник_аэродрома()
        {
            this.Используемая_экипировка = new HashSet<Используемая_экипировка>();
            this.Сотрудник_Воздушное_судно = new HashSet<Сотрудник_Воздушное_судно>();
        }
        [Display(Name = "ID Сотрудника")]
        public int ID_Сотрудника { get; set; }
        [Required(ErrorMessage = "Введите фамилию")]
        public string Фамилия { get; set; }
        [Required(ErrorMessage = "Введите имя")]
        public string Имя { get; set; }
        [Required(ErrorMessage = "Введите отчество")]
        public string Отчество { get; set; }
        public bool Пол { get; set; }
        [Display(Name = "Дата рождения")]
        [DataType(DataType.Date)]
        public DateTime Дата_рождения { get; set; }
        public long Телефон { get; set; }
        [Display(Name = "Военное звание")]
        [Required(ErrorMessage = "Введите военное звание")]
        public string Военное_звание { get; set; }
        [Required(ErrorMessage = "Введите должность")]
        public string Должность { get; set; }
        [Display(Name = "Место работы")]
        [Required(ErrorMessage = "Введите место работы")]
        public string Место_работы { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Используемая_экипировка> Используемая_экипировка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудник_Воздушное_судно> Сотрудник_Воздушное_судно { get; set; }
    }
}
