//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryAirfield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Сотрудник_Воздушное_судно
    {
        public int ID { get; set; }
        [Display(Name = "ID Сотрудника")]
        public int ID_Сотрудника { get; set; }
        [Display(Name = "ID Воздушного судна")]
        public int ID_Воздушного_судна { get; set; }
    
        public virtual Воздушное_судно Воздушное_судно { get; set; }
        public virtual Сотрудник_аэродрома Сотрудник_аэродрома { get; set; }
    }
}
