//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryAirfield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Топливная_система
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Топливная_система()
        {
            this.Воздушное_судно = new HashSet<Воздушное_судно>();
        }
        [Display(Name = "ID топливной системы")]
        public int ID_топливной_системы { get; set; }
        [Display(Name = "Масса топлива (кг)")]
        public int Масса_топлива_в_кг_ { get; set; }
        [Display(Name = "Вид топлива")]
        [Required(ErrorMessage = "Введите вид топлива")]
        public string Вид_топлива { get; set; }
        [Display(Name = "Способ заправки")]
        [Required(ErrorMessage = "Введите способ заправки")]
        public string Способ_заправки { get; set; }
        [Display(Name = "Количество баков")]
        public int Количество_баков { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Воздушное_судно> Воздушное_судно { get; set; }
    }
}
