//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryAirfield.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Узлы_маневрирования
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Узлы_маневрирования()
        {
            this.Воздушное_судно = new HashSet<Воздушное_судно>();
        }

        [Display(Name = "ID узлов маневрирования")]
        public int ID_узлов_маневрирования { get; set; }
        [Display(Name = "Размах крыла (м)")]
        public int Размах_крыла_в_м_ { get; set; }
        [Display(Name = "Наличие закрылок")]
        public bool Наличие_закрылок { get; set; }
        [Display(Name = "Угол стреловидности")]
        public Nullable<int> Угол_стреловидности { get; set; }
        [Display(Name = "Скороподъёмность (м/с)")]
        public int Скороподъемность_в_м_с_ { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Воздушное_судно> Воздушное_судно { get; set; }
    }
}
